### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by dwhitmore** [donnelljenkins/aurelia-datagrid#13]
Keep getting the following error:

Unhandled promise rejection Error: Loader must implement loadTemplate(url).
    at Loader.loadTemplate (http://localhost:9000/jspm_packages/npm/aurelia-loader@1.0.0-beta.1.1.1/aurelia-loader.js:118:13)
    at ensureRegistryEntry (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:2643:19)
    at ViewEngine.loadViewFactory (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:2706:14)
    at ConventionalViewStrategy.loadViewFactory (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:526:25)
    at HtmlBehaviorResource.load (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:3440:29)
    at ResourceDescription.load (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:2351:28)
    at ResourceModule.load (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:2299:35)
    at http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:2638:43
    at g (http://localhost:9000/jspm_packages/npm/core-js@2.0.3/client/shim.min.js:1921:85)
    at http://localhost:9000/jspm_packages/npm/core-js@2.0.3/client/shim.min.js:1926:19

**Comment by dwhitmore** [comment]
Should have tried a simple update first...
